### PR TITLE
Merge lastest hie-bios (with incoming master release 0.13)

### PR DESCRIPTION
**Pull request by jneira**
* I've not able to build it with `stack-8.2.2.yaml` due a conflicts between the installed `Cabal` and the haddock-api

### CODE REVIEW

**Comment by fendor** [comment]
Merged in https://github.com/mpickering/haskell-ide-engine/pull/41

**Comment by jneira** [comment]
Mmm, maybe i am missing some git foo but this branch still needs to be rebased or merged with https://github.com/mpickering/haskell-ide-engine before merge the pull requests, no? The [pr](https://github.com/mpickering/haskell-ide-engine/pull/26) is pointing that there are conflicting files.

**Comment by fendor** [comment]
Right c-h-h needs to be rebased, but the changes are in mpickering/hie-bios, right?

**Comment by jneira** [comment]
@fendor sorry for not comment out before it but the pr had some other minor changes:
* checkout the lastest master in the cabal-helper-submodule to avoid a build error in windows
* remove an unused import to avoid a build error with stack (due a `-Werror-`)
* add clock-0.7.2 to stack-8.6.5.yaml

(they can be added after a rebase)

> Right c-h-h needs to be rebased, but the changes are in mpickering/hie-bios, right?

yeah, i think with a rebase you will see cleaner the pr but i think the result (and the work) would be the same (modulo the merge commit).

**Pull request closed without merging**
